platform :ios, "12.0"
flutter_application_path = '../my_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
 
target 'ProjectObjectiveC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 
  # Pods for flutter_demo_ios
  install_all_flutter_pods(flutter_application_path)
  
  pod 'SDWebImage'
end
 
post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end